In [1]:
import torch
import torch.nn as nn

In [2]:
from embedding_players import get_embeddings

torch.Size([26786, 165]) torch.Size([26786, 165]) torch.Size([26786, 13])


C:\Users\lachl\anaconda3\envs\ml\lib\site-packages\IPython\core\interactiveshell.py:3418: DtypeWarning: Columns (14) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\lachl\Google Drive\Uni Year 5\git_stuff\STAT3007Project\embedding_players.py:47: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ret_val[wicket_title] = 1 * (ret_val["wicket_kind"] == wicket_title)


# Device

In [3]:
# torch.cuda.is_available() checks and returns a Boolean True if a GPU is available, else it'll return False
is_cuda = torch.cuda.is_available()

# If we have a GPU available, we'll set our device to GPU. We'll use this device variable later in our code.
if is_cuda:
    device = torch.device("cuda")
    print("GPU is available")
else:
    device = torch.device("cpu")
    print("GPU not available, CPU used")

GPU not available, CPU used


# Filepaths

In [4]:
BBB_filepath = "C:/Users/lachl/Google Drive/Uni Year 5/git_stuff/STAT3007Project/csv_files/cricsheet_data_partial.csv"

# Import embeddings

In [5]:
#, bowl_at_ball, model, results, pitch
bat_at_ball, bowl_at_ball, model, results, pitch, df = get_embeddings(raw_data_file_name=BBB_filepath)

Epoch 0: train loss: 0.6752440929412842
Epoch 1: train loss: 0.6713957190513611
Epoch 2: train loss: 0.6675800085067749
Epoch 3: train loss: 0.6637951731681824
Epoch 4: train loss: 0.6600391864776611
Epoch 5: train loss: 0.6563103795051575
Epoch 6: train loss: 0.6526069045066833
Epoch 7: train loss: 0.6489271521568298
Epoch 8: train loss: 0.645269513130188
Epoch 9: train loss: 0.6416324377059937
Epoch 10: train loss: 0.6380143761634827
Epoch 11: train loss: 0.6344138979911804
Epoch 12: train loss: 0.6308295726776123
Epoch 13: train loss: 0.627260148525238
Epoch 14: train loss: 0.6237040162086487
Epoch 15: train loss: 0.6201599836349487
Epoch 16: train loss: 0.6166269183158875
Epoch 17: train loss: 0.613103449344635
Epoch 18: train loss: 0.6095883846282959
Epoch 19: train loss: 0.6060804724693298
Epoch 20: train loss: 0.6025786399841309
Epoch 21: train loss: 0.5990816950798035
Epoch 22: train loss: 0.5955886244773865
Epoch 23: train loss: 0.5920981168746948
Epoch 24: train loss: 0.58860

Epoch 199: train loss: 0.15290570259094238
Epoch 200: train loss: 0.1524822860956192
Epoch 201: train loss: 0.15206721425056458
Epoch 202: train loss: 0.1516602486371994
Epoch 203: train loss: 0.15126118063926697
Epoch 204: train loss: 0.15086981654167175
Epoch 205: train loss: 0.15048599243164062
Epoch 206: train loss: 0.15010949969291687
Epoch 207: train loss: 0.14974014461040497
Epoch 208: train loss: 0.14937780797481537
Epoch 209: train loss: 0.14902228116989136
Epoch 210: train loss: 0.1486733853816986
Epoch 211: train loss: 0.14833101630210876
Epoch 212: train loss: 0.1479949802160263
Epoch 213: train loss: 0.1476651281118393
Epoch 214: train loss: 0.14734134078025818
Epoch 215: train loss: 0.14702342450618744
Epoch 216: train loss: 0.1467113047838211
Epoch 217: train loss: 0.14640478789806366
Epoch 218: train loss: 0.14610376954078674
Epoch 219: train loss: 0.1458081156015396
Epoch 220: train loss: 0.1455177217721939
Epoch 221: train loss: 0.1452324539422989
Epoch 222: train los

Epoch 396: train loss: 0.12709040939807892
Epoch 397: train loss: 0.1270565241575241
Epoch 398: train loss: 0.12702293694019318
Epoch 399: train loss: 0.12698963284492493
Epoch 400: train loss: 0.12695659697055817
Epoch 401: train loss: 0.1269238293170929
Epoch 402: train loss: 0.1268913447856903
Epoch 403: train loss: 0.1268591284751892
Epoch 404: train loss: 0.1268271803855896
Epoch 405: train loss: 0.12679550051689148
Epoch 406: train loss: 0.12676408886909485
Epoch 407: train loss: 0.12673290073871613
Epoch 408: train loss: 0.12670201063156128
Epoch 409: train loss: 0.12667137384414673
Epoch 410: train loss: 0.1266409456729889
Epoch 411: train loss: 0.12661078572273254
Epoch 412: train loss: 0.1265808790922165
Epoch 413: train loss: 0.12655121088027954
Epoch 414: train loss: 0.1265217661857605
Epoch 415: train loss: 0.12649257481098175
Epoch 416: train loss: 0.1264636069536209
Epoch 417: train loss: 0.12643487751483917
Epoch 418: train loss: 0.12640638649463654
Epoch 419: train los

In [6]:
bat_emb = bat_at_ball.shape[1]
bowl_emb = bowl_at_ball.shape[1]


all_game_ids = df["game_id"].unique()

each_game = {}

for game_id in all_game_ids:
    indexes = df["game_id"] == game_id
    num_in_go = sum(indexes)
    
    in_values = torch.cat([bat_at_ball[indexes], bowl_at_ball[indexes]], 1).reshape(num_in_go,1, bat_emb+bowl_emb)
    
    each_game[game_id] = (in_values, results[indexes], pitch[indexes])

In [7]:
next(iter(each_game.values()))[0]

tensor([[[-0.5102,  1.1968, -0.2728,  ...,  2.1892,  0.6875,  0.0693]],

        [[-0.5102,  1.1968, -0.2728,  ...,  2.1892,  0.6875,  0.0693]],

        [[-0.5102,  1.1968, -0.2728,  ...,  2.1892,  0.6875,  0.0693]],

        ...,

        [[-0.5067,  1.2022, -0.3001,  ...,  2.2395,  0.6769,  0.0490]],

        [[-0.5992,  1.1219, -0.2616,  ...,  2.1535,  0.6816,  0.1065]],

        [[-0.5258,  1.1834, -0.3055,  ...,  2.1535,  0.6816,  0.1065]]],
       grad_fn=<ReshapeAliasBackward0>)

# Define RNN model

adapted from https://blog.floydhub.com/a-beginners-guide-on-recurrent-neural-networks-with-pytorch/


In [65]:
class Model(nn.Module):
    def __init__(self, bowl_dim, batt_dim, output_size, hidden_dim, n_layers):
        super(Model, self).__init__()

        # Defining some parameters
        self.hidden_dim = hidden_dim
        self.n_layers = n_layers

        #Defining the layers
        # RNN Layer
    
        self.rnn = nn.RNN(bowl_dim + batt_dim, hidden_dim, n_layers, batch_first=True)   
        # Fully connected layer
        self.fc = nn.Linear(hidden_dim, output_size)
        
        self.sig = torch.nn.Sigmoid()
    
    def forward(self, x):
        
        batch_size = x.size(0)

        # Initializing hidden state for first input using method defined below
        hidden = self.init_hidden(batch_size)

        # Passing in the input and hidden state into the model and obtaining outputs
        out, hidden = self.rnn(x, hidden)

        # Reshaping the outputs such that it can be fit into the fully connected layer
        out = out.contiguous().view(-1, self.hidden_dim)
        out = self.fc(out)
        
        return self.sig(out)
    
    def init_hidden(self, batch_size):
        # This method generates the first hidden state of zeros which we'll use in the forward pass
        # We'll send the tensor holding the hidden state to the device we specified earlier as well
        hidden = torch.zeros(self.n_layers, batch_size, self.hidden_dim)
        return hidden


In [66]:
# Instantiate the model with hyperparameters
model = Model(bowl_dim = 10, batt_dim=10, output_size=13, hidden_dim=100, n_layers=3)
# We'll also set the model to the device that we defined earlier (default is CPU)
model.to(device)

# Define hyperparameters

lr=0.01

# Define Loss, Optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=lr)

In [67]:
model(next(iter(each_game.values()))[0])

tensor([[0.4873, 0.4760, 0.4989,  ..., 0.5212, 0.4879, 0.5319],
        [0.4873, 0.4760, 0.4989,  ..., 0.5212, 0.4879, 0.5319],
        [0.4873, 0.4760, 0.4989,  ..., 0.5212, 0.4879, 0.5319],
        ...,
        [0.4881, 0.4760, 0.4996,  ..., 0.5204, 0.4881, 0.5321],
        [0.4871, 0.4750, 0.4996,  ..., 0.5192, 0.4878, 0.5315],
        [0.4874, 0.4754, 0.4987,  ..., 0.5196, 0.4868, 0.5324]],
       grad_fn=<SigmoidBackward0>)

In [68]:
# Training Run
n_epochs = 1000
for epoch in range(1, n_epochs + 1):
    if epoch%1 == 0:
        print('Epoch: {}/{}.............'.format(epoch, n_epochs), end=' ')
        print("Loss: {:.4f}".format(loss.item()))
    
    optimizer.zero_grad() # Clears existing gradients from previous epoch
    #input_seq.to(device)
    for embeds, results, ground in each_game.values():
        
        pred = model(embeds)
    
        loss = criterion(pred, results)
        loss.backward(retain_graph=True) # Does backpropagation and calculates gradients
        optimizer.step() # Updates the weights accordingly

Epoch: 1/1000............. Loss: 0.0332
Epoch: 2/1000............. Loss: 0.2434
Epoch: 3/1000............. Loss: 0.2282
Epoch: 4/1000............. Loss: 0.2129
Epoch: 5/1000............. Loss: 0.1966
Epoch: 6/1000............. Loss: 0.1784
Epoch: 7/1000............. Loss: 0.1585
Epoch: 8/1000............. Loss: 0.1374
Epoch: 9/1000............. Loss: 0.1166
Epoch: 10/1000............. Loss: 0.0980
Epoch: 11/1000............. Loss: 0.0827
Epoch: 12/1000............. Loss: 0.0710
Epoch: 13/1000............. Loss: 0.0625
Epoch: 14/1000............. Loss: 0.0563
Epoch: 15/1000............. Loss: 0.0518
Epoch: 16/1000............. Loss: 0.0485
Epoch: 17/1000............. Loss: 0.0460
Epoch: 18/1000............. Loss: 0.0441
Epoch: 19/1000............. Loss: 0.0426
Epoch: 20/1000............. Loss: 0.0414
Epoch: 21/1000............. Loss: 0.0404
Epoch: 22/1000............. Loss: 0.0397
Epoch: 23/1000............. Loss: 0.0390
Epoch: 24/1000............. Loss: 0.0385
Epoch: 25/1000...........

KeyboardInterrupt: 

In [53]:
model(next(iter(each_game.values()))[0])

tensor([[0.7352, 0.1507, 0.0345,  ..., 0.0214, 0.0207, 0.0211],
        [0.7352, 0.1507, 0.0345,  ..., 0.0214, 0.0207, 0.0211],
        [0.7352, 0.1507, 0.0345,  ..., 0.0214, 0.0207, 0.0211],
        ...,
        [0.7353, 0.1507, 0.0346,  ..., 0.0215, 0.0207, 0.0211],
        [0.7348, 0.1510, 0.0348,  ..., 0.0216, 0.0209, 0.0213],
        [0.7349, 0.1513, 0.0348,  ..., 0.0216, 0.0209, 0.0213]],
       grad_fn=<SigmoidBackward0>)

In [54]:
next(iter(each_game.values()))[1]

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.]])