In [1]:
import torch
import torch.nn as nn

In [2]:
from embedding_players import get_embeddings

torch.Size([26786, 165]) torch.Size([26786, 165]) torch.Size([26786, 13])


C:\Users\lachl\anaconda3\envs\ml\lib\site-packages\IPython\core\interactiveshell.py:3418: DtypeWarning: Columns (14) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\lachl\Google Drive\Uni Year 5\git_stuff\STAT3007Project\embedding_players.py:47: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ret_val[wicket_title] = 1 * (ret_val["wicket_kind"] == wicket_title)


# Device

In [3]:
# torch.cuda.is_available() checks and returns a Boolean True if a GPU is available, else it'll return False
is_cuda = torch.cuda.is_available()

# If we have a GPU available, we'll set our device to GPU. We'll use this device variable later in our code.
if is_cuda:
    device = torch.device("cuda")
    print("GPU is available")
else:
    device = torch.device("cpu")
    print("GPU not available, CPU used")

GPU not available, CPU used


# Filepaths

In [4]:
BBB_filepath = "C:/Users/lachl/Google Drive/Uni Year 5/git_stuff/STAT3007Project/csv_files/cricsheet_data_partial.csv"

# Import embeddings

In [5]:
#, bowl_at_ball, model, results, pitch
bat_at_ball, bowl_at_ball, model, results, pitch, df = get_embeddings(raw_data_file_name=BBB_filepath)

Epoch 0: train loss: 0.7310588359832764
Epoch 1: train loss: 0.7261393070220947
Epoch 2: train loss: 0.7212622761726379
Epoch 3: train loss: 0.7164236307144165
Epoch 4: train loss: 0.7116196155548096
Epoch 5: train loss: 0.7068466544151306
Epoch 6: train loss: 0.7021014094352722
Epoch 7: train loss: 0.6973804235458374
Epoch 8: train loss: 0.6926807761192322
Epoch 9: train loss: 0.6879991888999939
Epoch 10: train loss: 0.6833328604698181
Epoch 11: train loss: 0.6786790490150452
Epoch 12: train loss: 0.6740350127220154
Epoch 13: train loss: 0.6693981289863586
Epoch 14: train loss: 0.6647658348083496
Epoch 15: train loss: 0.6601359248161316
Epoch 16: train loss: 0.6555059552192688
Epoch 17: train loss: 0.650873601436615
Epoch 18: train loss: 0.646236777305603
Epoch 19: train loss: 0.6415933966636658
Epoch 20: train loss: 0.6369416117668152
Epoch 21: train loss: 0.6322792172431946
Epoch 22: train loss: 0.627604603767395
Epoch 23: train loss: 0.6229159235954285
Epoch 24: train loss: 0.61821

Epoch 196: train loss: 0.14392228424549103
Epoch 197: train loss: 0.14363478124141693
Epoch 198: train loss: 0.14335282146930695
Epoch 199: train loss: 0.14307624101638794
Epoch 200: train loss: 0.14280492067337036
Epoch 201: train loss: 0.14253869652748108
Epoch 202: train loss: 0.14227744936943054
Epoch 203: train loss: 0.1420210748910904
Epoch 204: train loss: 0.14176946878433228
Epoch 205: train loss: 0.14152248203754425
Epoch 206: train loss: 0.14127998054027557
Epoch 207: train loss: 0.14104193449020386
Epoch 208: train loss: 0.1408081352710724
Epoch 209: train loss: 0.14057858288288116
Epoch 210: train loss: 0.14035311341285706
Epoch 211: train loss: 0.1401316374540329
Epoch 212: train loss: 0.13991406559944153
Epoch 213: train loss: 0.13970030844211578
Epoch 214: train loss: 0.1394902914762497
Epoch 215: train loss: 0.1392839103937149
Epoch 216: train loss: 0.13908106088638306
Epoch 217: train loss: 0.13888171315193176
Epoch 218: train loss: 0.13868574798107147
Epoch 219: train

Epoch 390: train loss: 0.1258651465177536
Epoch 391: train loss: 0.12583909928798676
Epoch 392: train loss: 0.12581327557563782
Epoch 393: train loss: 0.1257876753807068
Epoch 394: train loss: 0.12576226890087128
Epoch 395: train loss: 0.12573707103729248
Epoch 396: train loss: 0.1257120668888092
Epoch 397: train loss: 0.12568727135658264
Epoch 398: train loss: 0.1256626844406128
Epoch 399: train loss: 0.12563827633857727
Epoch 400: train loss: 0.12561409175395966
Epoch 401: train loss: 0.12559007108211517
Epoch 402: train loss: 0.1255662590265274
Epoch 403: train loss: 0.12554262578487396
Epoch 404: train loss: 0.12551918625831604
Epoch 405: train loss: 0.12549594044685364
Epoch 406: train loss: 0.12547285854816437
Epoch 407: train loss: 0.12544997036457062
Epoch 408: train loss: 0.12542724609375
Epoch 409: train loss: 0.1254047155380249
Epoch 410: train loss: 0.12538234889507294
Epoch 411: train loss: 0.1253601610660553
Epoch 412: train loss: 0.12533815205097198
Epoch 413: train loss

In [13]:
bat_emb = bat_at_ball.shape[1]
bowl_emb = bowl_at_ball.shape[1]


all_game_ids = df["game_id"].unique()

each_game = {}

for game_id in all_game_ids:
    indexes = df["game_id"] == game_id
    num_in_go = sum(indexes)
    
    in_values = torch.cat([bat_at_ball[indexes], bowl_at_ball[indexes]], 1).reshape(num_in_go,1, bat_emb+bowl_emb)
    
    each_game[game_id] = (in_values, results[indexes], pitch[indexes][0])

In [14]:
next(iter(each_game.values()))[2]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [8]:
next(iter(each_game.values()))[1]

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.]])

# Define RNN model

adapted from https://blog.floydhub.com/a-beginners-guide-on-recurrent-neural-networks-with-pytorch/


In [15]:
class Model(nn.Module):
    def __init__(self, bowl_dim, batt_dim, output_size, hidden_dim, n_layers):
        super(Model, self).__init__()

        # Defining some parameters
        self.hidden_dim = hidden_dim
        self.n_layers = n_layers

        #Defining the layers
        # RNN Layer
    
        self.rnn = nn.RNN(bowl_dim + batt_dim, hidden_dim, n_layers, batch_first=True)   
        # Fully connected layer
        self.fc = nn.Linear(hidden_dim, output_size)
        
        self.sig = torch.nn.Sigmoid()
    
    def forward(self, x):
        
        batch_size = x.size(0)

        # Initializing hidden state for first input using method defined below
        hidden = self.init_hidden(batch_size)

        # Passing in the input and hidden state into the model and obtaining outputs
        out, hidden = self.rnn(x, hidden)

        # Reshaping the outputs such that it can be fit into the fully connected layer
        out = out.contiguous().view(-1, self.hidden_dim)
        out = self.fc(out)
        
        return self.sig(out)
    
    def init_hidden(self, batch_size):
        # This method generates the first hidden state of zeros which we'll use in the forward pass
        # We'll send the tensor holding the hidden state to the device we specified earlier as well
        hidden = torch.zeros(self.n_layers, batch_size, self.hidden_dim)
        return hidden


In [16]:
# Instantiate the model with hyperparameters
model = Model(bowl_dim = 10, batt_dim=10, output_size=13, hidden_dim=100, n_layers=3)
# We'll also set the model to the device that we defined earlier (default is CPU)
model.to(device)

# Define hyperparameters

lr=0.01

# Define Loss, Optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=lr)

In [17]:
model(next(iter(each_game.values()))[0])

tensor([[0.4724, 0.4633, 0.4997,  ..., 0.5361, 0.5150, 0.4683],
        [0.4724, 0.4633, 0.4997,  ..., 0.5361, 0.5150, 0.4683],
        [0.4724, 0.4633, 0.4997,  ..., 0.5361, 0.5150, 0.4683],
        ...,
        [0.4712, 0.4621, 0.5011,  ..., 0.5343, 0.5146, 0.4690],
        [0.4721, 0.4648, 0.4994,  ..., 0.5356, 0.5141, 0.4687],
        [0.4718, 0.4641, 0.4994,  ..., 0.5354, 0.5144, 0.4690]],
       grad_fn=<SigmoidBackward0>)

In [18]:
# Training Run
n_epochs = 1000
for epoch in range(1, n_epochs + 1):
    
    optimizer.zero_grad() # Clears existing gradients from previous epoch
    #input_seq.to(device)
    for embeds, results, ground in each_game.values():
        
        pred = model(embeds)
    
        loss = criterion(pred, results)
        loss.backward(retain_graph=True) # Does backpropagation and calculates gradients
        optimizer.step() # Updates the weights accordingly
        
    if epoch%10 == 1:
        print('Epoch: {}/{}.............'.format(epoch, n_epochs), end=' ')
        print("Loss: {:.4f}".format(loss.item()))

Epoch: 1/1000............. 

NameError: name 'loss' is not defined

In [ ]:
model(next(iter(each_game.values()))[0])

In [ ]:
next(iter(each_game.values()))[1]